all:
	inkscape -z -e ../app/src/main/res/drawable-mdpi/ic_launcher.png -w 48 -h 48 merde.svg
	inkscape -z -e ../app/src/main/res/drawable-hdpi/ic_launcher.png -w 72 -h 72 merde.svg
	inkscape -z -e ../app/src/main/res/drawable-xhdpi/ic_launcher.png -w 96 -h 96 merde.svg
	inkscape -z -e ../app/src/main/res/drawable-xxhdpi/ic_launcher.png -w 144 -h 144 merde.svg
